//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentacion.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ALUMNO.
        /// </summary>
        internal static string btnAlumno {
            get {
                return ResourceManager.GetString("btnAlumno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesion.
        /// </summary>
        internal static string btnCerrarSesion {
            get {
                return ResourceManager.GetString("btnCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a    Chat.
        /// </summary>
        internal static string btnChat {
            get {
                return ResourceManager.GetString("btnChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultas.
        /// </summary>
        internal static string btnConsultas {
            get {
                return ResourceManager.GetString("btnConsultas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DOCENTE.
        /// </summary>
        internal static string btnDocente {
            get {
                return ResourceManager.GetString("btnDocente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupos.
        /// </summary>
        internal static string btnGrupos {
            get {
                return ResourceManager.GetString("btnGrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INICIAR SESIÓN.
        /// </summary>
        internal static string btnIniciar {
            get {
                return ResourceManager.GetString("btnIniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a   Perfil.
        /// </summary>
        internal static string btnPerfil {
            get {
                return ResourceManager.GetString("btnPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADMINISTRADOR.
        /// </summary>
        internal static string btnRegistrar {
            get {
                return ResourceManager.GetString("btnRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string btnRegistrarse {
            get {
                return ResourceManager.GetString("btnRegistrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tienes una cuenta? Presiona aqui:.
        /// </summary>
        internal static string lblCuenta {
            get {
                return ResourceManager.GetString("lblCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string lblErrorRegistro {
            get {
                return ResourceManager.GetString("lblErrorRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido, ¿a donde desea dirigirse?.
        /// </summary>
        internal static string lblInicio {
            get {
                return ResourceManager.GetString("lblInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu principal.
        /// </summary>
        internal static string lblPrincipal {
            get {
                return ResourceManager.GetString("lblPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AREA DE REGISTRO ALUMNO.
        /// </summary>
        internal static string lblRegistroA {
            get {
                return ResourceManager.GetString("lblRegistroA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AREA DE REGISTRO DOCENTE.
        /// </summary>
        internal static string lblRegistroD {
            get {
                return ResourceManager.GetString("lblRegistroD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INICIO SESIÓN ALUMNO.
        /// </summary>
        internal static string lblSesionA {
            get {
                return ResourceManager.GetString("lblSesionA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INICIO SESIÓN DOCENTE.
        /// </summary>
        internal static string lblSesionD {
            get {
                return ResourceManager.GetString("lblSesionD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesion.
        /// </summary>
        internal static string LinkIniciar {
            get {
                return ResourceManager.GetString("LinkIniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a user(1)1.
        /// </summary>
        internal static string pictureBox1 {
            get {
                return ResourceManager.GetString("pictureBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string Registrarse {
            get {
                return ResourceManager.GetString("Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a APELLIDO.
        /// </summary>
        internal static string txtApellido {
            get {
                return ResourceManager.GetString("txtApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CEDULA.
        /// </summary>
        internal static string txtCedula {
            get {
                return ResourceManager.GetString("txtCedula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONFIRMAR CONTRASEÑA.
        /// </summary>
        internal static string txtConfirmacion {
            get {
                return ResourceManager.GetString("txtConfirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONTRASEÑA.
        /// </summary>
        internal static string txtContraseña {
            get {
                return ResourceManager.GetString("txtContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GRUPO.
        /// </summary>
        internal static string txtGrupo {
            get {
                return ResourceManager.GetString("txtGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MATERIA.
        /// </summary>
        internal static string txtMateria {
            get {
                return ResourceManager.GetString("txtMateria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOMBRE.
        /// </summary>
        internal static string txtNombre {
            get {
                return ResourceManager.GetString("txtNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOMBRE USUARIO.
        /// </summary>
        internal static string txtNombreUser {
            get {
                return ResourceManager.GetString("txtNombreUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a USUARIO.
        /// </summary>
        internal static string txtUsuario {
            get {
                return ResourceManager.GetString("txtUsuario", resourceCulture);
            }
        }
    }
}
